//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ActionDatas.proto
namespace ActionDatas
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionDatastable")]
  public partial class ActionDatastable : global::ProtoBuf.IExtensible
  {
    public ActionDatastable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<ActionDatas> _tlist = new global::System.Collections.Generic.List<ActionDatas>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ActionDatas> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionDatas")]
  public partial class ActionDatas : global::ProtoBuf.IExtensible
  {
    public ActionDatas() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private bool _IgnoreMove = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IgnoreMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IgnoreMove
    {
      get { return _IgnoreMove; }
      set { _IgnoreMove = value; }
    }
    private bool _IgnoreGravity = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IgnoreGravity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IgnoreGravity
    {
      get { return _IgnoreGravity; }
      set { _IgnoreGravity = value; }
    }
    private bool _IgnoreCollision = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"IgnoreCollision", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IgnoreCollision
    {
      get { return _IgnoreCollision; }
      set { _IgnoreCollision = value; }
    }
    private bool _IgnoreXZVelocity = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"IgnoreXZVelocity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IgnoreXZVelocity
    {
      get { return _IgnoreXZVelocity; }
      set { _IgnoreXZVelocity = value; }
    }
    private bool _IgnoreXZMove = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"IgnoreXZMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IgnoreXZMove
    {
      get { return _IgnoreXZMove; }
      set { _IgnoreXZMove = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}