//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: InputDatas.proto
namespace InputDatas
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InputDatastable")]
  public partial class InputDatastable : global::ProtoBuf.IExtensible
  {
    public InputDatastable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<InputDatas> _tlist = new global::System.Collections.Generic.List<InputDatas>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<InputDatas> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InputDatas")]
  public partial class InputDatas : global::ProtoBuf.IExtensible
  {
    public InputDatas() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Lines = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Lines", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Lines
    {
      get { return _Lines; }
      set { _Lines = value; }
    }
    private string _LinesAir = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LinesAir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LinesAir
    {
      get { return _LinesAir; }
      set { _LinesAir = value; }
    }
    private string _InputString = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"InputString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string InputString
    {
      get { return _InputString; }
      set { _InputString = value; }
    }
    private int _DelayFrame = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"DelayFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DelayFrame
    {
      get { return _DelayFrame; }
      set { _DelayFrame = value; }
    }
    private string _Desc = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Desc
    {
      get { return _Desc; }
      set { _Desc = value; }
    }
    private string _DescExtra = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"DescExtra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DescExtra
    {
      get { return _DescExtra; }
      set { _DescExtra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}