//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WeaponDatas.proto
namespace WeaponDatas
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeaponDatastable")]
  public partial class WeaponDatastable : global::ProtoBuf.IExtensible
  {
    public WeaponDatastable() {}
    
    private string _tname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tname
    {
      get { return _tname; }
      set { _tname = value; }
    }
    private readonly global::System.Collections.Generic.List<WeaponDatas> _tlist = new global::System.Collections.Generic.List<WeaponDatas>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WeaponDatas> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeaponDatas")]
  public partial class WeaponDatas : global::ProtoBuf.IExtensible
  {
    public WeaponDatas() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _WeaponL = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"WeaponL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string WeaponL
    {
      get { return _WeaponL; }
      set { _WeaponL = value; }
    }
    private string _TextureL = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TextureL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TextureL
    {
      get { return _TextureL; }
      set { _TextureL = value; }
    }
    private string _WeaponR = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"WeaponR", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string WeaponR
    {
      get { return _WeaponR; }
      set { _WeaponR = value; }
    }
    private string _TextureR = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"TextureR", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string TextureR
    {
      get { return _TextureR; }
      set { _TextureR = value; }
    }
    private string _PosAWL = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"PosAWL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PosAWL
    {
      get { return _PosAWL; }
      set { _PosAWL = value; }
    }
    private string _PosAWR = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"PosAWR", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PosAWR
    {
      get { return _PosAWR; }
      set { _PosAWR = value; }
    }
    private string _PosBWL = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"PosBWL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PosBWL
    {
      get { return _PosBWL; }
      set { _PosBWL = value; }
    }
    private string _PosBWR = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"PosBWR", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PosBWR
    {
      get { return _PosBWR; }
      set { _PosBWR = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}