// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;  
using System.Collections;  
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;
using System.Text;
public class GenVersionInfo
{

//	public static string ApplicationVersionPath = Application.dataPath.Replace("Assets","Versions");
//
//	[MenuItem("Build/Resource/TableInfo")]
//	static void GenTableVersionInfo(){
//		//string ApplicationVersionPath = Application.dataPath.Replace("Assets/","Versions");
//		string tablePath = Application.dataPath +"/Table/Resources/";
//		string CopyToDir = ApplicationVersionPath +"/Table/Resources/";
//		string WriteToFile = ApplicationVersionPath +"/Table_version.txt";
//		string[] files = Directory.GetFiles(tablePath);
//		StringBuilder builder = new StringBuilder();
//
//		ResourceManager.Instance.CreateDirs(CopyToDir);
//
//		foreach(string file in files){
//			if(file.EndsWith(".txt")){
//				string fileName = file.Substring(file.LastIndexOf("/")+1);
//				string str = "";
//
//				//byte[] bytes = File.ReadAllBytes(file);
//				string text = File.ReadAllText(file,Encoding.UTF8);
//				byte[] bytes = EncryptUtil.EncodeData(System.Text.Encoding.UTF8.GetBytes(text));
//
//				File.WriteAllBytes(CopyToDir+fileName,bytes);
//
//				builder.Append("{ \"file\": \"Table/Resources/"+fileName+"\",\"ftype\":2, \"ver\": 1 },\r\n");
//			}
//		}
//
//		File.WriteAllText(WriteToFile,builder.ToString());
//
//		EditorUtility.DisplayDialog("TableInfo", "Build TableInfo", "Ok");
//	}
	/*
	[MenuItem("Build/Resource/ReadTableInfo")]
	static void ReadTableInfo(){
		string CopyToDir = ApplicationVersionPath +"/Table/Resources/";
		//string[] files = Directory.GetFiles(CopyToDir);

		//foreach(string file in files){
		byte[] bytes = File.ReadAllBytes(CopyToDir+"BattleBase.txt");

			bytes = EncryptUtil.DecodeData(bytes);

			string text = System.Text.Encoding.UTF8.GetString(bytes);
			System.Console.WriteLine (text);
		//}
	}
	*/
}


