// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public class GameColor
{
	public static Color Green1
	{
		get{return new Color(72f/255f,162f/255f,136f/255f);}
	}

	public static Color Green2
	{
		get{return new Color(36f/255f,214f/255f,181f/255f);}
	}

	public static Color Green3
	{
		get{return new Color(8f/255f,252f/255f,31f/255f);}
	}


	public static Color Gray1
	{
		get{return new Color(190f/255f,193f/255f,190f/255f);}
	}

	public static Color Yellow1
	{
		get{return new Color(250f/255f,199f/255f,125f/255f);}
	}
	public static Color Yellow2
	{
		get{return new Color(255f/255f,241f/255f,31f/255f);}
	}
	public static Color Yellow3
	{
		get{return new Color(255f/255f,221f/255f,86f/255f);}
	}

	public static Color Red1
	{
		get{return new Color(255f/255f,33f/255f,33f/255f);}
	}


	public static Color Purple1
	{
		get{return new Color(169f/255f,47f/255f,255f/255f);}
	}

	public enum GColor
	{
		None = 0,
		Green1 =1,
		Green2=2,
		Green3=3,


		Gray1=10,

		Yellow1=21,
		Yellow2=22,
		Yellow3=23,

		Red1=31,

		Purple1=41,
	}


	public static Color GetColor(GColor idx)
	{
		switch(idx)
		{
		case GColor.Green1:
			return Green1;

		case GColor.Green2:
			return Green2;
		case GColor.Green3:
			return Green3;

		case GColor.Gray1:
			return Gray1;
		case GColor.Yellow1:
			return Yellow1;
		case GColor.Yellow2:
			return Yellow2;
		case GColor.Yellow3:
			return Yellow3;

		case GColor.Red1:
			return Red1;

		case GColor.Purple1:
			return Purple1;
		}

		return Color.black;
	}
}


