//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MeteorMsg")]
  public partial class MeteorMsg : global::ProtoBuf.IExtensible
  {
    public MeteorMsg() {}
    
    private MeteorMsg.MsgType _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MeteorMsg.MsgType cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProtocolVerify", Value=10)]
      ProtocolVerify = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoomReq", Value=100)]
      GetRoomReq = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoomRsp", Value=101)]
      GetRoomRsp = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomReq", Value=102)]
      CreateRoomReq = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomRsp", Value=103)]
      CreateRoomRsp = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomReq", Value=104)]
      JoinRoomReq = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomRsp", Value=105)]
      JoinRoomRsp = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInRoomReq", Value=120)]
      ChatInRoomReq = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInRoomRsp", Value=121)]
      ChatInRoomRsp = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInLobbyReq", Value=122)]
      ChatInLobbyReq = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInLobbyRsp", Value=123)]
      ChatInLobbyRsp = 123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterQueueReq", Value=124)]
      EnterQueueReq = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterQueueRsp", Value=125)]
      EnterQueueRsp = 125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitQueueReq", Value=126)]
      ExitQueueReq = 126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitQueueRsp", Value=127)]
      ExitQueueRsp = 127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueueMsgWaitReady", Value=128)]
      QueueMsgWaitReady = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueueMsgCanceled", Value=129)]
      QueueMsgCanceled = 129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QueueMsgReadyReq", Value=130)]
      QueueMsgReadyReq = 130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleBegin", Value=131)]
      OnBattleBegin = 131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleCancel", Value=132)]
      OnBattleCancel = 132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserSelectRole", Value=133)]
      UserSelectRole = 133,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnUserSelectRole", Value=134)]
      OnUserSelectRole = 134,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserSelectSkill", Value=135)]
      UserSelectSkill = 135,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnUserSelectSkill", Value=136)]
      OnUserSelectSkill = 136,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserSelectSkin", Value=137)]
      UserSelectSkin = 137,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnUserSelectSkin", Value=138)]
      OnUserSelectSkin = 138,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserQuit", Value=139)]
      UserQuit = 139,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleEnterLevel", Value=140)]
      OnBattleEnterLevel = 140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleLoading", Value=141)]
      OnBattleLoading = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleStart", Value=142)]
      OnBattleStart = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleResult", Value=143)]
      OnBattleResult = 143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnBattleResultDetail", Value=144)]
      OnBattleResultDetail = 144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerQuit", Value=146)]
      OnPlayerQuit = 146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerReStart", Value=147)]
      OnPlayerReStart = 147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerFetchInput", Value=148)]
      OnPlayerFetchInput = 148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerReConnect", Value=149)]
      OnPlayerReConnect = 149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AudioChat", Value=150)]
      AudioChat = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncCommand", Value=888)]
      SyncCommand = 888
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Command")]
    public enum Command
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncRandomSeed", Value=1)]
      SyncRandomSeed = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KeyDown", Value=2)]
      KeyDown = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KeyUp", Value=3)]
      KeyUp = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KeyLast", Value=4)]
      KeyLast = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpawnPlayer", Value=5)]
      SpawnPlayer = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DestroyPlayer", Value=6)]
      DestroyPlayer = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoyStickMove", Value=7)]
      JoyStickMove = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MouseMove", Value=8)]
      MouseMove = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EquipWeapon", Value=9)]
      EquipWeapon = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DropWeapon", Value=10)]
      DropWeapon = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SellItem", Value=11)]
      SellItem = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyItem", Value=12)]
      BuyItem = 12
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncInitData")]
  public partial class SyncInitData : global::ProtoBuf.IExtensible
  {
    public SyncInitData() {}
    
    private uint _randomSeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"randomSeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint randomSeed
    {
      get { return _randomSeed; }
      set { _randomSeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEventData")]
  public partial class PlayerEventData : global::ProtoBuf.IExtensible
  {
    public PlayerEventData() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _camp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private uint _model;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model
    {
      get { return _model; }
      set { _model = value; }
    }
    private uint _weapon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"weapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon
    {
      get { return _weapon; }
      set { _weapon = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterQueueRsp")]
  public partial class EnterQueueRsp : global::ProtoBuf.IExtensible
  {
    public EnterQueueRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _playerInQueue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerInQueue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerInQueue
    {
      get { return _playerInQueue; }
      set { _playerInQueue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnBattleBegin")]
  public partial class OnBattleBegin : global::ProtoBuf.IExtensible
  {
    public OnBattleBegin() {}
    
    private readonly global::System.Collections.Generic.List<uint> _TeamMemberAId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"TeamMemberAId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> TeamMemberAId
    {
      get { return _TeamMemberAId; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _TeamMemberBId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"TeamMemberBId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> TeamMemberBId
    {
      get { return _TeamMemberBId; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _TeamMemberA = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"TeamMemberA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> TeamMemberA
    {
      get { return _TeamMemberA; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _TeamMemberB = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"TeamMemberB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> TeamMemberB
    {
      get { return _TeamMemberB; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSelectRole")]
  public partial class UserSelectRole : global::ProtoBuf.IExtensible
  {
    public UserSelectRole() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _HeroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSelectSkill")]
  public partial class UserSelectSkill : global::ProtoBuf.IExtensible
  {
    public UserSelectSkill() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _SkillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSelectSkin")]
  public partial class UserSelectSkin : global::ProtoBuf.IExtensible
  {
    public UserSelectSkin() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _Skin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Skin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Skin
    {
      get { return _Skin; }
      set { _Skin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnBattleCanceled")]
  public partial class OnBattleCanceled : global::ProtoBuf.IExtensible
  {
    public OnBattleCanceled() {}
    
    private uint _reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnBattleLoading")]
  public partial class OnBattleLoading : global::ProtoBuf.IExtensible
  {
    public OnBattleLoading() {}
    
    private readonly global::System.Collections.Generic.List<uint> _playerId = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> playerId
    {
      get { return _playerId; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _percent = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> percent
    {
      get { return _percent; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnBattleResult")]
  public partial class OnBattleResult : global::ProtoBuf.IExtensible
  {
    public OnBattleResult() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSellItem")]
  public partial class PlayerSellItem : global::ProtoBuf.IExtensible
  {
    public PlayerSellItem() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBuyItem")]
  public partial class PlayerBuyItem : global::ProtoBuf.IExtensible
  {
    public PlayerBuyItem() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolVerifyReq")]
  public partial class ProtocolVerifyReq : global::ProtoBuf.IExtensible
  {
    public ProtocolVerifyReq() {}
    
    private uint _protocol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint protocol
    {
      get { return _protocol; }
      set { _protocol = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolVerifyRsp")]
  public partial class ProtocolVerifyRsp : global::ProtoBuf.IExtensible
  {
    public ProtocolVerifyRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private RoomInfo.RoomRule _rule;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomRule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private RoomInfo.RoomPattern _pattern;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomPattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private uint _hpMax;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private uint _password;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint password
    {
      get { return _password; }
      set { _password = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private uint _Group1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Group1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Group1
    {
      get { return _Group1; }
      set { _Group1 = value; }
    }
    private uint _Group2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Group2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Group2
    {
      get { return _Group2; }
      set { _Group2 = value; }
    }
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _maxPlayer;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"maxPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxPlayer
    {
      get { return _maxPlayer; }
      set { _maxPlayer = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RoomRule")]
    public enum RoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MZ", Value=1)]
      MZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROB", Value=2)]
      ROB = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Defence", Value=3)]
      Defence = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillTarget", Value=4)]
      KillTarget = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Endless", Value=5)]
      Endless = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=6)]
      Normal = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Story", Value=7)]
      Story = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Moba", Value=8)]
      Moba = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomPattern")]
    public enum RoomPattern
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"_Normal", Value=1)]
      _Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"_Record", Value=2)]
      _Record = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"_Replay", Value=3)]
      _Replay = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MeteorVersion")]
    public enum MeteorVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"V107", Value=1)]
      V107 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"V907", Value=2)]
      V907 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomNotExist", Value=1)]
      RoomNotExist = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomPlayerFull", Value=2)]
      RoomPlayerFull = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomNeedPassword", Value=3)]
      RoomNeedPassword = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomVersionErr", Value=4)]
      RoomVersionErr = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserInAnotherRoom", Value=5)]
      UserInAnotherRoom = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomFull", Value=6)]
      RoomFull = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoomRsp")]
  public partial class GetRoomRsp : global::ProtoBuf.IExtensible
  {
    public GetRoomRsp() {}
    
    private readonly global::System.Collections.Generic.List<RoomInfo> _RoomInLobby = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"RoomInLobby", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> RoomInLobby
    {
      get { return _RoomInLobby; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomReq")]
  public partial class CreateRoomReq : global::ProtoBuf.IExtensible
  {
    public CreateRoomReq() {}
    
    private RoomInfo.RoomPattern _pattern;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomPattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private uint _maxPlayer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxPlayer
    {
      get { return _maxPlayer; }
      set { _maxPlayer = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private RoomInfo.RoomRule _rule;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomRule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private uint _hpMax;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private uint _roundTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"roundTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundTime
    {
      get { return _roundTime; }
      set { _roundTime = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _secret = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"secret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string secret
    {
      get { return _secret; }
      set { _secret = value; }
    }
    private byte[] _replay_data = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"replay_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] replay_data
    {
      get { return _replay_data; }
      set { _replay_data = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _models = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"models", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> models
    {
      get { return _models; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _weapons = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"weapons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> weapons
    {
      get { return _weapons; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomRsp")]
  public partial class CreateRoomRsp : global::ProtoBuf.IExtensible
  {
    public CreateRoomRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _levelId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomReq")]
  public partial class JoinRoomReq : global::ProtoBuf.IExtensible
  {
    public JoinRoomReq() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomRsp")]
  public partial class JoinRoomRsp : global::ProtoBuf.IExtensible
  {
    public JoinRoomRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _models = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"models", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> models
    {
      get { return _models; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _weapons = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"weapons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> weapons
    {
      get { return _weapons; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector2_")]
  public partial class Vector2_ : global::ProtoBuf.IExtensible
  {
    public Vector2_() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameCommand")]
  public partial class FrameCommand : global::ProtoBuf.IExtensible
  {
    public FrameCommand() {}
    
    private uint _LogicFrame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LogicFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LogicFrame
    {
      get { return _LogicFrame; }
      set { _LogicFrame = value; }
    }
    private uint _playerId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private MeteorMsg.Command _command;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MeteorMsg.Command command
    {
      get { return _command; }
      set { _command = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFrames")]
  public partial class GameFrames : global::ProtoBuf.IExtensible
  {
    public GameFrames() {}
    
    private readonly global::System.Collections.Generic.List<FrameCommand> _commands = new global::System.Collections.Generic.List<FrameCommand>();
    [global::ProtoBuf.ProtoMember(1, Name=@"commands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FrameCommand> commands
    {
      get { return _commands; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMsg")]
  public partial class ChatMsg : global::ProtoBuf.IExtensible
  {
    public ChatMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _channelType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"channelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint channelType
    {
      get { return _channelType; }
      set { _channelType = value; }
    }
    private string _chatMessage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"chatMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string chatMessage
    {
      get { return _chatMessage; }
      set { _chatMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioChatMsg")]
  public partial class AudioChatMsg : global::ProtoBuf.IExtensible
  {
    public AudioChatMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _audio_data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"audio_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] audio_data
    {
      get { return _audio_data; }
      set { _audio_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}