//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MeteorMsg")]
  public partial class MeteorMsg : global::ProtoBuf.IExtensible
  {
    public MeteorMsg() {}
    
    private MeteorMsg.MsgType _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MeteorMsg.MsgType cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MsgType")]
    public enum MsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ProtocolVerify", Value=10)]
      ProtocolVerify = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AliveUpdate", Value=11)]
      AliveUpdate = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoomReq", Value=100)]
      GetRoomReq = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetRoomRsp", Value=101)]
      GetRoomRsp = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomReq", Value=102)]
      CreateRoomReq = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRoomRsp", Value=103)]
      CreateRoomRsp = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomReq", Value=104)]
      JoinRoomReq = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JoinRoomRsp", Value=105)]
      JoinRoomRsp = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerJoinRoom", Value=106)]
      OnPlayerJoinRoom = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInRoomReq", Value=107)]
      ChatInRoomReq = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatInRoomRsp", Value=108)]
      ChatInRoomRsp = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterLevelReq", Value=109)]
      EnterLevelReq = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerEnterLevel", Value=110)]
      OnPlayerEnterLevel = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterLevelRsp", Value=111)]
      EnterLevelRsp = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LeaveLevelReq", Value=112)]
      LeaveLevelReq = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnPlayerLeaveLevel", Value=113)]
      OnPlayerLeaveLevel = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AudioChat", Value=114)]
      AudioChat = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SyncRate", Value=115)]
      SyncRate = 115
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Command")]
    public enum Command
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ClientSync", Value=1)]
      ClientSync = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerSync", Value=2)]
      ServerSync = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewTurn", Value=3)]
      NewTurn = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Drop", Value=4)]
      Drop = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Use", Value=5)]
      Use = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Weapon", Value=6)]
      Weapon = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UIWeapon", Value=7)]
      UIWeapon = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Kill", Value=8)]
      Kill = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pause", Value=9)]
      Pause = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UIModel", Value=10)]
      UIModel = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UIAddNpc", Value=11)]
      UIAddNpc = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNpc", Value=12)]
      AddNpc = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartSnow", Value=13)]
      StartSnow = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StopSnow", Value=14)]
      StopSnow = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetPosition", Value=15)]
      ResetPosition = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveTo", Value=16)]
      MoveTo = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GetItem", Value=17)]
      GetItem = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Kick", Value=18)]
      Kick = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Skick", Value=19)]
      Skick = 19
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerEvent")]
  public partial class PlayerEvent : global::ProtoBuf.IExtensible
  {
    public PlayerEvent() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _camp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private uint _model;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model
    {
      get { return _model; }
      set { _model = value; }
    }
    private uint _weapon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"weapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon
    {
      get { return _weapon; }
      set { _weapon = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _spawnIndex = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"spawnIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint spawnIndex
    {
      get { return _spawnIndex; }
      set { _spawnIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OperateMsg")]
  public partial class OperateMsg : global::ProtoBuf.IExtensible
  {
    public OperateMsg() {}
    
    private uint _KillTarget;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"KillTarget", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint KillTarget
    {
      get { return _KillTarget; }
      set { _KillTarget = value; }
    }
    private uint _Operate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Operate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Operate
    {
      get { return _Operate; }
      set { _Operate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DropMsg")]
  public partial class DropMsg : global::ProtoBuf.IExtensible
  {
    public DropMsg() {}
    
    private uint _item;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item
    {
      get { return _item; }
      set { _item = value; }
    }
    private _Vector3 _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public _Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private _Vector3 _forward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"forward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public _Vector3 forward
    {
      get { return _forward; }
      set { _forward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetItemMsg")]
  public partial class GetItemMsg : global::ProtoBuf.IExtensible
  {
    public GetItemMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _instance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"instance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint instance
    {
      get { return _instance; }
      set { _instance = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSync")]
  public partial class PlayerSync : global::ProtoBuf.IExtensible
  {
    public PlayerSync() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _model;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model
    {
      get { return _model; }
      set { _model = value; }
    }
    private uint _weapon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"weapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon
    {
      get { return _weapon; }
      set { _weapon = value; }
    }
    private uint _weapon1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"weapon1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon1
    {
      get { return _weapon1; }
      set { _weapon1 = value; }
    }
    private uint _camp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private uint _hp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _ang;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ang
    {
      get { return _ang; }
      set { _ang = value; }
    }
    private uint _spwanIndex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"spwanIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint spwanIndex
    {
      get { return _spwanIndex; }
      set { _spwanIndex = value; }
    }
    private _Vector3 _position = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public _Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private _Quaternion _rotation = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public _Quaternion rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _buff = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"buff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> buff
    {
      get { return _buff; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolVerifyReq")]
  public partial class ProtocolVerifyReq : global::ProtoBuf.IExtensible
  {
    public ProtocolVerifyReq() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolVerifyRsp")]
  public partial class ProtocolVerifyRsp : global::ProtoBuf.IExtensible
  {
    public ProtocolVerifyRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private uint _player;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private RoomInfo.RoomRule _rule;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomRule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private RoomInfo.RoomPattern _pattern;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomPattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private uint _hpMax;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private uint _password;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint password
    {
      get { return _password; }
      set { _password = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private uint _Group1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Group1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Group1
    {
      get { return _Group1; }
      set { _Group1 = value; }
    }
    private uint _Group2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Group2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Group2
    {
      get { return _Group2; }
      set { _Group2 = value; }
    }
    private uint _playerCount;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private uint _maxPlayer;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"maxPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxPlayer
    {
      get { return _maxPlayer; }
      set { _maxPlayer = value; }
    }
    private uint _owner;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _models = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(14, Name=@"models", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> models
    {
      get { return _models; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomRule")]
    public enum RoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MZ", Value=1)]
      MZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROB", Value=2)]
      ROB = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Defence", Value=3)]
      Defence = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KillTarget", Value=4)]
      KillTarget = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Endless", Value=5)]
      Endless = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=6)]
      Normal = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Story", Value=7)]
      Story = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Moba", Value=8)]
      Moba = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomPattern")]
    public enum RoomPattern
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"_Normal", Value=1)]
      _Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"_Replay", Value=2)]
      _Replay = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MeteorVersion")]
    public enum MeteorVersion
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"V107", Value=1)]
      V107 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"V907", Value=2)]
      V907 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoomRsp")]
  public partial class GetRoomRsp : global::ProtoBuf.IExtensible
  {
    public GetRoomRsp() {}
    
    private readonly global::System.Collections.Generic.List<RoomInfo> _Rooms = new global::System.Collections.Generic.List<RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RoomInfo> Rooms
    {
      get { return _Rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomReq")]
  public partial class CreateRoomReq : global::ProtoBuf.IExtensible
  {
    public CreateRoomReq() {}
    
    private RoomInfo.RoomPattern _pattern;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomPattern pattern
    {
      get { return _pattern; }
      set { _pattern = value; }
    }
    private uint _maxPlayer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxPlayer
    {
      get { return _maxPlayer; }
      set { _maxPlayer = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private RoomInfo.RoomRule _rule;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.RoomRule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private uint _hpMax;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private uint _roundTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"roundTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundTime
    {
      get { return _roundTime; }
      set { _roundTime = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _models = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"models", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> models
    {
      get { return _models; }
    }
  
    private string _secret = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"secret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string secret
    {
      get { return _secret; }
      set { _secret = value; }
    }
    private byte[] _replay_data = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"replay_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] replay_data
    {
      get { return _replay_data; }
      set { _replay_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomRsp")]
  public partial class CreateRoomRsp : global::ProtoBuf.IExtensible
  {
    public CreateRoomRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _levelId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomReq")]
  public partial class JoinRoomReq : global::ProtoBuf.IExtensible
  {
    public JoinRoomReq() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private RoomInfo.MeteorVersion _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomInfo.MeteorVersion version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _models = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"models", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> models
    {
      get { return _models; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomRsp")]
  public partial class JoinRoomRsp : global::ProtoBuf.IExtensible
  {
    public JoinRoomRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private uint _levelIdx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint levelIdx
    {
      get { return _levelIdx; }
      set { _levelIdx = value; }
    }
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnPlayerJoinRoom")]
  public partial class OnPlayerJoinRoom : global::ProtoBuf.IExtensible
  {
    public OnPlayerJoinRoom() {}
    
    private uint _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player
    {
      get { return _player; }
      set { _player = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnEnterLevelRsp")]
  public partial class OnEnterLevelRsp : global::ProtoBuf.IExtensible
  {
    public OnEnterLevelRsp() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerSync> _players = new global::System.Collections.Generic.List<PlayerSync>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerSync> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameCommand")]
  public partial class FrameCommand : global::ProtoBuf.IExtensible
  {
    public FrameCommand() {}
    
    private uint _playerId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private MeteorMsg.Command _command;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MeteorMsg.Command command
    {
      get { return _command; }
      set { _command = value; }
    }
    private byte[] _Data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameFrame")]
  public partial class GameFrame : global::ProtoBuf.IExtensible
  {
    public GameFrame() {}
    
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<FrameCommand> _commands = new global::System.Collections.Generic.List<FrameCommand>();
    [global::ProtoBuf.ProtoMember(2, Name=@"commands", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FrameCommand> commands
    {
      get { return _commands; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMsg")]
  public partial class ChatMsg : global::ProtoBuf.IExtensible
  {
    public ChatMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _chatMessage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chatMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string chatMessage
    {
      get { return _chatMessage; }
      set { _chatMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioChatMsg")]
  public partial class AudioChatMsg : global::ProtoBuf.IExtensible
  {
    public AudioChatMsg() {}
    
    private uint _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _audio_data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"audio_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] audio_data
    {
      get { return _audio_data; }
      set { _audio_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"_Vector3")]
  public partial class _Vector3 : global::ProtoBuf.IExtensible
  {
    public _Vector3() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"_Quaternion")]
  public partial class _Quaternion : global::ProtoBuf.IExtensible
  {
    public _Quaternion() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _w;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int w
    {
      get { return _w; }
      set { _w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncMsg")]
  public partial class SyncMsg : global::ProtoBuf.IExtensible
  {
    public SyncMsg() {}
    
    private int _syncrate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"syncrate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int syncrate
    {
      get { return _syncrate; }
      set { _syncrate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}